# .cargo-release.toml
shared-version = false
allow-branch = ["main"]
dependent-version = "upgrade"
push = true
tag = true
tag-name = "v{{version}}"
publish = true
release = false
workspace = true


# cargo release version 0.1.3 --workspace